/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db;


import com.rosyoki.spring.boot.sample.app.jooq.DefaultCatalog;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogDb extends SchemaImpl {

    private static final long serialVersionUID = 1071874220;

    /**
     * The reference instance of <code>blog_db</code>
     */
    public static final BlogDb BLOG_DB = new BlogDb();

    /**
     * The table <code>blog_db.auth_group</code>.
     */
    public final AuthGroup AUTH_GROUP = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup.AUTH_GROUP;

    /**
     * The table <code>blog_db.auth_group_permissions</code>.
     */
    public final AuthGroupPermissions AUTH_GROUP_PERMISSIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions.AUTH_GROUP_PERMISSIONS;

    /**
     * The table <code>blog_db.auth_permission</code>.
     */
    public final AuthPermission AUTH_PERMISSION = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission.AUTH_PERMISSION;

    /**
     * The table <code>blog_db.auth_user</code>.
     */
    public final AuthUser AUTH_USER = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser.AUTH_USER;

    /**
     * The table <code>blog_db.auth_user_groups</code>.
     */
    public final AuthUserGroups AUTH_USER_GROUPS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups.AUTH_USER_GROUPS;

    /**
     * The table <code>blog_db.auth_user_user_permissions</code>.
     */
    public final AuthUserUserPermissions AUTH_USER_USER_PERMISSIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS;

    /**
     * The table <code>blog_db.django_admin_log</code>.
     */
    public final DjangoAdminLog DJANGO_ADMIN_LOG = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog.DJANGO_ADMIN_LOG;

    /**
     * The table <code>blog_db.django_content_type</code>.
     */
    public final DjangoContentType DJANGO_CONTENT_TYPE = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType.DJANGO_CONTENT_TYPE;

    /**
     * The table <code>blog_db.django_migrations</code>.
     */
    public final DjangoMigrations DJANGO_MIGRATIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations.DJANGO_MIGRATIONS;

    /**
     * The table <code>blog_db.django_session</code>.
     */
    public final DjangoSession DJANGO_SESSION = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession.DJANGO_SESSION;

    /**
     * The table <code>blog_db.post_zip_data</code>.
     */
    public final PostZipData POST_ZIP_DATA = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData.POST_ZIP_DATA;

    /**
     * The table <code>blog_db.users</code>.
     */
    public final Users USERS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users.USERS;

    /**
     * The table <code>blog_db.user_detail</code>.
     */
    public final UserDetail USER_DETAIL = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail.USER_DETAIL;

    /**
     * No further instances allowed
     */
    private BlogDb() {
        super("blog_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AuthGroup.AUTH_GROUP,
            AuthGroupPermissions.AUTH_GROUP_PERMISSIONS,
            AuthPermission.AUTH_PERMISSION,
            AuthUser.AUTH_USER,
            AuthUserGroups.AUTH_USER_GROUPS,
            AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS,
            DjangoAdminLog.DJANGO_ADMIN_LOG,
            DjangoContentType.DJANGO_CONTENT_TYPE,
            DjangoMigrations.DJANGO_MIGRATIONS,
            DjangoSession.DJANGO_SESSION,
            PostZipData.POST_ZIP_DATA,
            Users.USERS,
            UserDetail.USER_DETAIL);
    }
}
