/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>blog_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTH_GROUP_NAME = Indexes0.AUTH_GROUP_NAME;
    public static final Index AUTH_GROUP_PRIMARY = Indexes0.AUTH_GROUP_PRIMARY;
    public static final Index AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ = Indexes0.AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ;
    public static final Index AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM = Indexes0.AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM;
    public static final Index AUTH_GROUP_PERMISSIONS_PRIMARY = Indexes0.AUTH_GROUP_PERMISSIONS_PRIMARY;
    public static final Index AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ = Indexes0.AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ;
    public static final Index AUTH_PERMISSION_PRIMARY = Indexes0.AUTH_PERMISSION_PRIMARY;
    public static final Index AUTH_USER_PRIMARY = Indexes0.AUTH_USER_PRIMARY;
    public static final Index AUTH_USER_USERNAME = Indexes0.AUTH_USER_USERNAME;
    public static final Index AUTH_USER_GROUPS_AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID = Indexes0.AUTH_USER_GROUPS_AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID;
    public static final Index AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ = Indexes0.AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ;
    public static final Index AUTH_USER_GROUPS_PRIMARY = Indexes0.AUTH_USER_GROUPS_PRIMARY;
    public static final Index AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ = Indexes0.AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ;
    public static final Index AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM = Indexes0.AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM;
    public static final Index AUTH_USER_USER_PERMISSIONS_PRIMARY = Indexes0.AUTH_USER_USER_PERMISSIONS_PRIMARY;
    public static final Index DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO = Indexes0.DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO;
    public static final Index DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK = Indexes0.DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK;
    public static final Index DJANGO_ADMIN_LOG_PRIMARY = Indexes0.DJANGO_ADMIN_LOG_PRIMARY;
    public static final Index DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ = Indexes0.DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ;
    public static final Index DJANGO_CONTENT_TYPE_PRIMARY = Indexes0.DJANGO_CONTENT_TYPE_PRIMARY;
    public static final Index DJANGO_MIGRATIONS_PRIMARY = Indexes0.DJANGO_MIGRATIONS_PRIMARY;
    public static final Index DJANGO_SESSION_DJANGO_SESSION_EXPIRE_DATE_A5C62663 = Indexes0.DJANGO_SESSION_DJANGO_SESSION_EXPIRE_DATE_A5C62663;
    public static final Index DJANGO_SESSION_PRIMARY = Indexes0.DJANGO_SESSION_PRIMARY;
    public static final Index POST_ZIP_DATA_CITY = Indexes0.POST_ZIP_DATA_CITY;
    public static final Index POST_ZIP_DATA_POST_CITY_INDEX = Indexes0.POST_ZIP_DATA_POST_CITY_INDEX;
    public static final Index POST_ZIP_DATA_POST_CITY_TOWN_INDEX = Indexes0.POST_ZIP_DATA_POST_CITY_TOWN_INDEX;
    public static final Index POST_ZIP_DATA_PRIMARY = Indexes0.POST_ZIP_DATA_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_USERS_ID_INDEX = Indexes0.USERS_USERS_ID_INDEX;
    public static final Index USER_DETAIL_EML_NAME = Indexes0.USER_DETAIL_EML_NAME;
    public static final Index USER_DETAIL_PRIMARY = Indexes0.USER_DETAIL_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTH_GROUP_NAME = Internal.createIndex("name", AuthGroup.AUTH_GROUP, new OrderField[] { AuthGroup.AUTH_GROUP.NAME }, true);
        public static Index AUTH_GROUP_PRIMARY = Internal.createIndex("PRIMARY", AuthGroup.AUTH_GROUP, new OrderField[] { AuthGroup.AUTH_GROUP.ID }, true);
        public static Index AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ = Internal.createIndex("auth_group_permissions_group_id_permission_id_0cd325b0_uniq", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, new OrderField[] { AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.GROUP_ID, AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.PERMISSION_ID }, true);
        public static Index AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM = Internal.createIndex("auth_group_permissio_permission_id_84c5c92e_fk_auth_perm", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, new OrderField[] { AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.PERMISSION_ID }, false);
        public static Index AUTH_GROUP_PERMISSIONS_PRIMARY = Internal.createIndex("PRIMARY", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, new OrderField[] { AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.ID }, true);
        public static Index AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ = Internal.createIndex("auth_permission_content_type_id_codename_01ab375a_uniq", AuthPermission.AUTH_PERMISSION, new OrderField[] { AuthPermission.AUTH_PERMISSION.CONTENT_TYPE_ID, AuthPermission.AUTH_PERMISSION.CODENAME }, true);
        public static Index AUTH_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", AuthPermission.AUTH_PERMISSION, new OrderField[] { AuthPermission.AUTH_PERMISSION.ID }, true);
        public static Index AUTH_USER_PRIMARY = Internal.createIndex("PRIMARY", AuthUser.AUTH_USER, new OrderField[] { AuthUser.AUTH_USER.ID }, true);
        public static Index AUTH_USER_USERNAME = Internal.createIndex("username", AuthUser.AUTH_USER, new OrderField[] { AuthUser.AUTH_USER.USERNAME }, true);
        public static Index AUTH_USER_GROUPS_AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID = Internal.createIndex("auth_user_groups_group_id_97559544_fk_auth_group_id", AuthUserGroups.AUTH_USER_GROUPS, new OrderField[] { AuthUserGroups.AUTH_USER_GROUPS.GROUP_ID }, false);
        public static Index AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ = Internal.createIndex("auth_user_groups_user_id_group_id_94350c0c_uniq", AuthUserGroups.AUTH_USER_GROUPS, new OrderField[] { AuthUserGroups.AUTH_USER_GROUPS.USER_ID, AuthUserGroups.AUTH_USER_GROUPS.GROUP_ID }, true);
        public static Index AUTH_USER_GROUPS_PRIMARY = Internal.createIndex("PRIMARY", AuthUserGroups.AUTH_USER_GROUPS, new OrderField[] { AuthUserGroups.AUTH_USER_GROUPS.ID }, true);
        public static Index AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ = Internal.createIndex("auth_user_user_permissions_user_id_permission_id_14a6b632_uniq", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, new OrderField[] { AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.USER_ID, AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.PERMISSION_ID }, true);
        public static Index AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM = Internal.createIndex("auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, new OrderField[] { AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.PERMISSION_ID }, false);
        public static Index AUTH_USER_USER_PERMISSIONS_PRIMARY = Internal.createIndex("PRIMARY", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, new OrderField[] { AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.ID }, true);
        public static Index DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO = Internal.createIndex("django_admin_log_content_type_id_c4bce8eb_fk_django_co", DjangoAdminLog.DJANGO_ADMIN_LOG, new OrderField[] { DjangoAdminLog.DJANGO_ADMIN_LOG.CONTENT_TYPE_ID }, false);
        public static Index DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK = Internal.createIndex("django_admin_log_user_id_c564eba6_fk", DjangoAdminLog.DJANGO_ADMIN_LOG, new OrderField[] { DjangoAdminLog.DJANGO_ADMIN_LOG.USER_ID }, false);
        public static Index DJANGO_ADMIN_LOG_PRIMARY = Internal.createIndex("PRIMARY", DjangoAdminLog.DJANGO_ADMIN_LOG, new OrderField[] { DjangoAdminLog.DJANGO_ADMIN_LOG.ID }, true);
        public static Index DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ = Internal.createIndex("django_content_type_app_label_model_76bd3d3b_uniq", DjangoContentType.DJANGO_CONTENT_TYPE, new OrderField[] { DjangoContentType.DJANGO_CONTENT_TYPE.APP_LABEL, DjangoContentType.DJANGO_CONTENT_TYPE.MODEL }, true);
        public static Index DJANGO_CONTENT_TYPE_PRIMARY = Internal.createIndex("PRIMARY", DjangoContentType.DJANGO_CONTENT_TYPE, new OrderField[] { DjangoContentType.DJANGO_CONTENT_TYPE.ID }, true);
        public static Index DJANGO_MIGRATIONS_PRIMARY = Internal.createIndex("PRIMARY", DjangoMigrations.DJANGO_MIGRATIONS, new OrderField[] { DjangoMigrations.DJANGO_MIGRATIONS.ID }, true);
        public static Index DJANGO_SESSION_DJANGO_SESSION_EXPIRE_DATE_A5C62663 = Internal.createIndex("django_session_expire_date_a5c62663", DjangoSession.DJANGO_SESSION, new OrderField[] { DjangoSession.DJANGO_SESSION.EXPIRE_DATE }, false);
        public static Index DJANGO_SESSION_PRIMARY = Internal.createIndex("PRIMARY", DjangoSession.DJANGO_SESSION, new OrderField[] { DjangoSession.DJANGO_SESSION.SESSION_KEY }, true);
        public static Index POST_ZIP_DATA_CITY = Internal.createIndex("city", PostZipData.POST_ZIP_DATA, new OrderField[] { PostZipData.POST_ZIP_DATA.CITY }, false);
        public static Index POST_ZIP_DATA_POST_CITY_INDEX = Internal.createIndex("post_city_index", PostZipData.POST_ZIP_DATA, new OrderField[] { PostZipData.POST_ZIP_DATA.CITY }, false);
        public static Index POST_ZIP_DATA_POST_CITY_TOWN_INDEX = Internal.createIndex("post_city_town_index", PostZipData.POST_ZIP_DATA, new OrderField[] { PostZipData.POST_ZIP_DATA.CITY, PostZipData.POST_ZIP_DATA.TOWN }, false);
        public static Index POST_ZIP_DATA_PRIMARY = Internal.createIndex("PRIMARY", PostZipData.POST_ZIP_DATA, new OrderField[] { PostZipData.POST_ZIP_DATA.ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_USERS_ID_INDEX = Internal.createIndex("users_id_index", Users.USERS, new OrderField[] { Users.USERS.ID }, false);
        public static Index USER_DETAIL_EML_NAME = Internal.createIndex("EML_NAME", UserDetail.USER_DETAIL, new OrderField[] { UserDetail.USER_DETAIL.EML_NAME, UserDetail.USER_DETAIL.EML_DOMAIN }, true);
        public static Index USER_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", UserDetail.USER_DETAIL, new OrderField[] { UserDetail.USER_DETAIL.USERS_ID }, true);
    }
}
