/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthGroupPermissionsRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthGroupRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthPermissionRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserGroupsRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserUserPermissionsRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoAdminLogRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoContentTypeRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoMigrationsRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoSessionRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.PostZipDataRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.UserDetailRecord;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>blog_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthGroupRecord, Integer> IDENTITY_AUTH_GROUP = Identities0.IDENTITY_AUTH_GROUP;
    public static final Identity<AuthGroupPermissionsRecord, Integer> IDENTITY_AUTH_GROUP_PERMISSIONS = Identities0.IDENTITY_AUTH_GROUP_PERMISSIONS;
    public static final Identity<AuthPermissionRecord, Integer> IDENTITY_AUTH_PERMISSION = Identities0.IDENTITY_AUTH_PERMISSION;
    public static final Identity<AuthUserRecord, Integer> IDENTITY_AUTH_USER = Identities0.IDENTITY_AUTH_USER;
    public static final Identity<AuthUserGroupsRecord, Integer> IDENTITY_AUTH_USER_GROUPS = Identities0.IDENTITY_AUTH_USER_GROUPS;
    public static final Identity<AuthUserUserPermissionsRecord, Integer> IDENTITY_AUTH_USER_USER_PERMISSIONS = Identities0.IDENTITY_AUTH_USER_USER_PERMISSIONS;
    public static final Identity<DjangoAdminLogRecord, Integer> IDENTITY_DJANGO_ADMIN_LOG = Identities0.IDENTITY_DJANGO_ADMIN_LOG;
    public static final Identity<DjangoContentTypeRecord, Integer> IDENTITY_DJANGO_CONTENT_TYPE = Identities0.IDENTITY_DJANGO_CONTENT_TYPE;
    public static final Identity<DjangoMigrationsRecord, Integer> IDENTITY_DJANGO_MIGRATIONS = Identities0.IDENTITY_DJANGO_MIGRATIONS;
    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthGroupRecord> KEY_AUTH_GROUP_PRIMARY = UniqueKeys0.KEY_AUTH_GROUP_PRIMARY;
    public static final UniqueKey<AuthGroupRecord> KEY_AUTH_GROUP_NAME = UniqueKeys0.KEY_AUTH_GROUP_NAME;
    public static final UniqueKey<AuthGroupPermissionsRecord> KEY_AUTH_GROUP_PERMISSIONS_PRIMARY = UniqueKeys0.KEY_AUTH_GROUP_PERMISSIONS_PRIMARY;
    public static final UniqueKey<AuthGroupPermissionsRecord> KEY_AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ = UniqueKeys0.KEY_AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ;
    public static final UniqueKey<AuthPermissionRecord> KEY_AUTH_PERMISSION_PRIMARY = UniqueKeys0.KEY_AUTH_PERMISSION_PRIMARY;
    public static final UniqueKey<AuthPermissionRecord> KEY_AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ = UniqueKeys0.KEY_AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ;
    public static final UniqueKey<AuthUserRecord> KEY_AUTH_USER_PRIMARY = UniqueKeys0.KEY_AUTH_USER_PRIMARY;
    public static final UniqueKey<AuthUserRecord> KEY_AUTH_USER_USERNAME = UniqueKeys0.KEY_AUTH_USER_USERNAME;
    public static final UniqueKey<AuthUserGroupsRecord> KEY_AUTH_USER_GROUPS_PRIMARY = UniqueKeys0.KEY_AUTH_USER_GROUPS_PRIMARY;
    public static final UniqueKey<AuthUserGroupsRecord> KEY_AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ = UniqueKeys0.KEY_AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ;
    public static final UniqueKey<AuthUserUserPermissionsRecord> KEY_AUTH_USER_USER_PERMISSIONS_PRIMARY = UniqueKeys0.KEY_AUTH_USER_USER_PERMISSIONS_PRIMARY;
    public static final UniqueKey<AuthUserUserPermissionsRecord> KEY_AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ = UniqueKeys0.KEY_AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ;
    public static final UniqueKey<DjangoAdminLogRecord> KEY_DJANGO_ADMIN_LOG_PRIMARY = UniqueKeys0.KEY_DJANGO_ADMIN_LOG_PRIMARY;
    public static final UniqueKey<DjangoContentTypeRecord> KEY_DJANGO_CONTENT_TYPE_PRIMARY = UniqueKeys0.KEY_DJANGO_CONTENT_TYPE_PRIMARY;
    public static final UniqueKey<DjangoContentTypeRecord> KEY_DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ = UniqueKeys0.KEY_DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ;
    public static final UniqueKey<DjangoMigrationsRecord> KEY_DJANGO_MIGRATIONS_PRIMARY = UniqueKeys0.KEY_DJANGO_MIGRATIONS_PRIMARY;
    public static final UniqueKey<DjangoSessionRecord> KEY_DJANGO_SESSION_PRIMARY = UniqueKeys0.KEY_DJANGO_SESSION_PRIMARY;
    public static final UniqueKey<PostZipDataRecord> KEY_POST_ZIP_DATA_PRIMARY = UniqueKeys0.KEY_POST_ZIP_DATA_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UserDetailRecord> KEY_USER_DETAIL_PRIMARY = UniqueKeys0.KEY_USER_DETAIL_PRIMARY;
    public static final UniqueKey<UserDetailRecord> KEY_USER_DETAIL_EML_NAME = UniqueKeys0.KEY_USER_DETAIL_EML_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthGroupPermissionsRecord, AuthGroupRecord> AUTH_GROUP_PERMISSIONS_GROUP_ID_B120CBF9_FK_AUTH_GROUP_ID = ForeignKeys0.AUTH_GROUP_PERMISSIONS_GROUP_ID_B120CBF9_FK_AUTH_GROUP_ID;
    public static final ForeignKey<AuthGroupPermissionsRecord, AuthPermissionRecord> AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM = ForeignKeys0.AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM;
    public static final ForeignKey<AuthPermissionRecord, DjangoContentTypeRecord> AUTH_PERMISSION_CONTENT_TYPE_ID_2F476E4B_FK_DJANGO_CO = ForeignKeys0.AUTH_PERMISSION_CONTENT_TYPE_ID_2F476E4B_FK_DJANGO_CO;
    public static final ForeignKey<AuthUserGroupsRecord, AuthUserRecord> AUTH_USER_GROUPS_USER_ID_6A12ED8B_FK_AUTH_USER_ID = ForeignKeys0.AUTH_USER_GROUPS_USER_ID_6A12ED8B_FK_AUTH_USER_ID;
    public static final ForeignKey<AuthUserGroupsRecord, AuthGroupRecord> AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID = ForeignKeys0.AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID;
    public static final ForeignKey<AuthUserUserPermissionsRecord, AuthUserRecord> AUTH_USER_USER_PERMISSIONS_USER_ID_A95EAD1B_FK_AUTH_USER_ID = ForeignKeys0.AUTH_USER_USER_PERMISSIONS_USER_ID_A95EAD1B_FK_AUTH_USER_ID;
    public static final ForeignKey<AuthUserUserPermissionsRecord, AuthPermissionRecord> AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM = ForeignKeys0.AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM;
    public static final ForeignKey<DjangoAdminLogRecord, DjangoContentTypeRecord> DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO = ForeignKeys0.DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO;
    public static final ForeignKey<DjangoAdminLogRecord, AuthUserRecord> DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK = ForeignKeys0.DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK;
    public static final ForeignKey<UserDetailRecord, UsersRecord> USER_DETAIL_IBFK_1 = ForeignKeys0.USER_DETAIL_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuthGroupRecord, Integer> IDENTITY_AUTH_GROUP = Internal.createIdentity(AuthGroup.AUTH_GROUP, AuthGroup.AUTH_GROUP.ID);
        public static Identity<AuthGroupPermissionsRecord, Integer> IDENTITY_AUTH_GROUP_PERMISSIONS = Internal.createIdentity(AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.ID);
        public static Identity<AuthPermissionRecord, Integer> IDENTITY_AUTH_PERMISSION = Internal.createIdentity(AuthPermission.AUTH_PERMISSION, AuthPermission.AUTH_PERMISSION.ID);
        public static Identity<AuthUserRecord, Integer> IDENTITY_AUTH_USER = Internal.createIdentity(AuthUser.AUTH_USER, AuthUser.AUTH_USER.ID);
        public static Identity<AuthUserGroupsRecord, Integer> IDENTITY_AUTH_USER_GROUPS = Internal.createIdentity(AuthUserGroups.AUTH_USER_GROUPS, AuthUserGroups.AUTH_USER_GROUPS.ID);
        public static Identity<AuthUserUserPermissionsRecord, Integer> IDENTITY_AUTH_USER_USER_PERMISSIONS = Internal.createIdentity(AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.ID);
        public static Identity<DjangoAdminLogRecord, Integer> IDENTITY_DJANGO_ADMIN_LOG = Internal.createIdentity(DjangoAdminLog.DJANGO_ADMIN_LOG, DjangoAdminLog.DJANGO_ADMIN_LOG.ID);
        public static Identity<DjangoContentTypeRecord, Integer> IDENTITY_DJANGO_CONTENT_TYPE = Internal.createIdentity(DjangoContentType.DJANGO_CONTENT_TYPE, DjangoContentType.DJANGO_CONTENT_TYPE.ID);
        public static Identity<DjangoMigrationsRecord, Integer> IDENTITY_DJANGO_MIGRATIONS = Internal.createIdentity(DjangoMigrations.DJANGO_MIGRATIONS, DjangoMigrations.DJANGO_MIGRATIONS.ID);
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthGroupRecord> KEY_AUTH_GROUP_PRIMARY = Internal.createUniqueKey(AuthGroup.AUTH_GROUP, "KEY_auth_group_PRIMARY", AuthGroup.AUTH_GROUP.ID);
        public static final UniqueKey<AuthGroupRecord> KEY_AUTH_GROUP_NAME = Internal.createUniqueKey(AuthGroup.AUTH_GROUP, "KEY_auth_group_name", AuthGroup.AUTH_GROUP.NAME);
        public static final UniqueKey<AuthGroupPermissionsRecord> KEY_AUTH_GROUP_PERMISSIONS_PRIMARY = Internal.createUniqueKey(AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, "KEY_auth_group_permissions_PRIMARY", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.ID);
        public static final UniqueKey<AuthGroupPermissionsRecord> KEY_AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ = Internal.createUniqueKey(AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, "KEY_auth_group_permissions_auth_group_permissions_group_id_permission_id_0cd325b0_uniq", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.GROUP_ID, AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.PERMISSION_ID);
        public static final UniqueKey<AuthPermissionRecord> KEY_AUTH_PERMISSION_PRIMARY = Internal.createUniqueKey(AuthPermission.AUTH_PERMISSION, "KEY_auth_permission_PRIMARY", AuthPermission.AUTH_PERMISSION.ID);
        public static final UniqueKey<AuthPermissionRecord> KEY_AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ = Internal.createUniqueKey(AuthPermission.AUTH_PERMISSION, "KEY_auth_permission_auth_permission_content_type_id_codename_01ab375a_uniq", AuthPermission.AUTH_PERMISSION.CONTENT_TYPE_ID, AuthPermission.AUTH_PERMISSION.CODENAME);
        public static final UniqueKey<AuthUserRecord> KEY_AUTH_USER_PRIMARY = Internal.createUniqueKey(AuthUser.AUTH_USER, "KEY_auth_user_PRIMARY", AuthUser.AUTH_USER.ID);
        public static final UniqueKey<AuthUserRecord> KEY_AUTH_USER_USERNAME = Internal.createUniqueKey(AuthUser.AUTH_USER, "KEY_auth_user_username", AuthUser.AUTH_USER.USERNAME);
        public static final UniqueKey<AuthUserGroupsRecord> KEY_AUTH_USER_GROUPS_PRIMARY = Internal.createUniqueKey(AuthUserGroups.AUTH_USER_GROUPS, "KEY_auth_user_groups_PRIMARY", AuthUserGroups.AUTH_USER_GROUPS.ID);
        public static final UniqueKey<AuthUserGroupsRecord> KEY_AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ = Internal.createUniqueKey(AuthUserGroups.AUTH_USER_GROUPS, "KEY_auth_user_groups_auth_user_groups_user_id_group_id_94350c0c_uniq", AuthUserGroups.AUTH_USER_GROUPS.USER_ID, AuthUserGroups.AUTH_USER_GROUPS.GROUP_ID);
        public static final UniqueKey<AuthUserUserPermissionsRecord> KEY_AUTH_USER_USER_PERMISSIONS_PRIMARY = Internal.createUniqueKey(AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, "KEY_auth_user_user_permissions_PRIMARY", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.ID);
        public static final UniqueKey<AuthUserUserPermissionsRecord> KEY_AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ = Internal.createUniqueKey(AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, "KEY_auth_user_user_permissions_auth_user_user_permissions_user_id_permission_id_14a6b632_uniq", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.USER_ID, AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.PERMISSION_ID);
        public static final UniqueKey<DjangoAdminLogRecord> KEY_DJANGO_ADMIN_LOG_PRIMARY = Internal.createUniqueKey(DjangoAdminLog.DJANGO_ADMIN_LOG, "KEY_django_admin_log_PRIMARY", DjangoAdminLog.DJANGO_ADMIN_LOG.ID);
        public static final UniqueKey<DjangoContentTypeRecord> KEY_DJANGO_CONTENT_TYPE_PRIMARY = Internal.createUniqueKey(DjangoContentType.DJANGO_CONTENT_TYPE, "KEY_django_content_type_PRIMARY", DjangoContentType.DJANGO_CONTENT_TYPE.ID);
        public static final UniqueKey<DjangoContentTypeRecord> KEY_DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ = Internal.createUniqueKey(DjangoContentType.DJANGO_CONTENT_TYPE, "KEY_django_content_type_django_content_type_app_label_model_76bd3d3b_uniq", DjangoContentType.DJANGO_CONTENT_TYPE.APP_LABEL, DjangoContentType.DJANGO_CONTENT_TYPE.MODEL);
        public static final UniqueKey<DjangoMigrationsRecord> KEY_DJANGO_MIGRATIONS_PRIMARY = Internal.createUniqueKey(DjangoMigrations.DJANGO_MIGRATIONS, "KEY_django_migrations_PRIMARY", DjangoMigrations.DJANGO_MIGRATIONS.ID);
        public static final UniqueKey<DjangoSessionRecord> KEY_DJANGO_SESSION_PRIMARY = Internal.createUniqueKey(DjangoSession.DJANGO_SESSION, "KEY_django_session_PRIMARY", DjangoSession.DJANGO_SESSION.SESSION_KEY);
        public static final UniqueKey<PostZipDataRecord> KEY_POST_ZIP_DATA_PRIMARY = Internal.createUniqueKey(PostZipData.POST_ZIP_DATA, "KEY_post_zip_data_PRIMARY", PostZipData.POST_ZIP_DATA.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
        public static final UniqueKey<UserDetailRecord> KEY_USER_DETAIL_PRIMARY = Internal.createUniqueKey(UserDetail.USER_DETAIL, "KEY_user_detail_PRIMARY", UserDetail.USER_DETAIL.USERS_ID);
        public static final UniqueKey<UserDetailRecord> KEY_USER_DETAIL_EML_NAME = Internal.createUniqueKey(UserDetail.USER_DETAIL, "KEY_user_detail_EML_NAME", UserDetail.USER_DETAIL.EML_NAME, UserDetail.USER_DETAIL.EML_DOMAIN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthGroupPermissionsRecord, AuthGroupRecord> AUTH_GROUP_PERMISSIONS_GROUP_ID_B120CBF9_FK_AUTH_GROUP_ID = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_GROUP_PRIMARY, AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.GROUP_ID);
        public static final ForeignKey<AuthGroupPermissionsRecord, AuthPermissionRecord> AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_PERMISSION_PRIMARY, AuthGroupPermissions.AUTH_GROUP_PERMISSIONS, "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm", AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.PERMISSION_ID);
        public static final ForeignKey<AuthPermissionRecord, DjangoContentTypeRecord> AUTH_PERMISSION_CONTENT_TYPE_ID_2F476E4B_FK_DJANGO_CO = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_DJANGO_CONTENT_TYPE_PRIMARY, AuthPermission.AUTH_PERMISSION, "auth_permission_content_type_id_2f476e4b_fk_django_co", AuthPermission.AUTH_PERMISSION.CONTENT_TYPE_ID);
        public static final ForeignKey<AuthUserGroupsRecord, AuthUserRecord> AUTH_USER_GROUPS_USER_ID_6A12ED8B_FK_AUTH_USER_ID = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_USER_PRIMARY, AuthUserGroups.AUTH_USER_GROUPS, "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id", AuthUserGroups.AUTH_USER_GROUPS.USER_ID);
        public static final ForeignKey<AuthUserGroupsRecord, AuthGroupRecord> AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_GROUP_PRIMARY, AuthUserGroups.AUTH_USER_GROUPS, "auth_user_groups_group_id_97559544_fk_auth_group_id", AuthUserGroups.AUTH_USER_GROUPS.GROUP_ID);
        public static final ForeignKey<AuthUserUserPermissionsRecord, AuthUserRecord> AUTH_USER_USER_PERMISSIONS_USER_ID_A95EAD1B_FK_AUTH_USER_ID = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_USER_PRIMARY, AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.USER_ID);
        public static final ForeignKey<AuthUserUserPermissionsRecord, AuthPermissionRecord> AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_PERMISSION_PRIMARY, AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS, "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm", AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS.PERMISSION_ID);
        public static final ForeignKey<DjangoAdminLogRecord, DjangoContentTypeRecord> DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_DJANGO_CONTENT_TYPE_PRIMARY, DjangoAdminLog.DJANGO_ADMIN_LOG, "django_admin_log_content_type_id_c4bce8eb_fk_django_co", DjangoAdminLog.DJANGO_ADMIN_LOG.CONTENT_TYPE_ID);
        public static final ForeignKey<DjangoAdminLogRecord, AuthUserRecord> DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_AUTH_USER_PRIMARY, DjangoAdminLog.DJANGO_ADMIN_LOG, "django_admin_log_user_id_c564eba6_fk", DjangoAdminLog.DJANGO_ADMIN_LOG.USER_ID);
        public static final ForeignKey<UserDetailRecord, UsersRecord> USER_DETAIL_IBFK_1 = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys.KEY_USERS_PRIMARY, UserDetail.USER_DETAIL, "user_detail_ibfk_1", UserDetail.USER_DETAIL.USERS_ID);
    }
}
