/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in blog_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blog_db.auth_group</code>.
     */
    public static final AuthGroup AUTH_GROUP = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroup.AUTH_GROUP;

    /**
     * The table <code>blog_db.auth_group_permissions</code>.
     */
    public static final AuthGroupPermissions AUTH_GROUP_PERMISSIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions.AUTH_GROUP_PERMISSIONS;

    /**
     * The table <code>blog_db.auth_permission</code>.
     */
    public static final AuthPermission AUTH_PERMISSION = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthPermission.AUTH_PERMISSION;

    /**
     * The table <code>blog_db.auth_user</code>.
     */
    public static final AuthUser AUTH_USER = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUser.AUTH_USER;

    /**
     * The table <code>blog_db.auth_user_groups</code>.
     */
    public static final AuthUserGroups AUTH_USER_GROUPS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserGroups.AUTH_USER_GROUPS;

    /**
     * The table <code>blog_db.auth_user_user_permissions</code>.
     */
    public static final AuthUserUserPermissions AUTH_USER_USER_PERMISSIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS;

    /**
     * The table <code>blog_db.django_admin_log</code>.
     */
    public static final DjangoAdminLog DJANGO_ADMIN_LOG = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog.DJANGO_ADMIN_LOG;

    /**
     * The table <code>blog_db.django_content_type</code>.
     */
    public static final DjangoContentType DJANGO_CONTENT_TYPE = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType.DJANGO_CONTENT_TYPE;

    /**
     * The table <code>blog_db.django_migrations</code>.
     */
    public static final DjangoMigrations DJANGO_MIGRATIONS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoMigrations.DJANGO_MIGRATIONS;

    /**
     * The table <code>blog_db.django_session</code>.
     */
    public static final DjangoSession DJANGO_SESSION = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession.DJANGO_SESSION;

    /**
     * The table <code>blog_db.post_zip_data</code>.
     */
    public static final PostZipData POST_ZIP_DATA = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData.POST_ZIP_DATA;

    /**
     * The table <code>blog_db.users</code>.
     */
    public static final Users USERS = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.Users.USERS;

    /**
     * The table <code>blog_db.user_detail</code>.
     */
    public static final UserDetail USER_DETAIL = com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail.USER_DETAIL;
}
