/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.public_;


import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index EML_NAME_INDEX_F = Indexes0.EML_NAME_INDEX_F;
    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index USERS_ID_INDEX = Indexes0.USERS_ID_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_8 = Internal.createIndex("primary_key_8", PostZipData.POST_ZIP_DATA, new OrderField[] { PostZipData.POST_ZIP_DATA.ID }, true);
        public static Index EML_NAME_INDEX_F = Internal.createIndex("eml_name_index_f", UserDetail.USER_DETAIL, new OrderField[] { UserDetail.USER_DETAIL.EML_NAME, UserDetail.USER_DETAIL.EML_DOMAIN }, true);
        public static Index PRIMARY_KEY_F = Internal.createIndex("primary_key_f", UserDetail.USER_DETAIL, new OrderField[] { UserDetail.USER_DETAIL.USERS_ID }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("primary_key_4", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_ID_INDEX = Internal.createIndex("users_id_index", Users.USERS, new OrderField[] { Users.USERS.ID }, false);
    }
}
