/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.public_;


import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.records.PostZipDataRecord;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.records.UserDetailRecord;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PostZipDataRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<UserDetailRecord> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;
    public static final UniqueKey<UserDetailRecord> EML_NAME = UniqueKeys0.EML_NAME;
    public static final UniqueKey<UsersRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserDetailRecord, UsersRecord> USER_DETAIL_IBFK_1 = ForeignKeys0.USER_DETAIL_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PostZipDataRecord> CONSTRAINT_8 = Internal.createUniqueKey(PostZipData.POST_ZIP_DATA, "constraint_8", PostZipData.POST_ZIP_DATA.ID);
        public static final UniqueKey<UserDetailRecord> CONSTRAINT_F = Internal.createUniqueKey(UserDetail.USER_DETAIL, "constraint_f", UserDetail.USER_DETAIL.USERS_ID);
        public static final UniqueKey<UserDetailRecord> EML_NAME = Internal.createUniqueKey(UserDetail.USER_DETAIL, "eml_name", UserDetail.USER_DETAIL.EML_NAME, UserDetail.USER_DETAIL.EML_DOMAIN);
        public static final UniqueKey<UsersRecord> CONSTRAINT_4 = Internal.createUniqueKey(Users.USERS, "constraint_4", Users.USERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserDetailRecord, UsersRecord> USER_DETAIL_IBFK_1 = Internal.createForeignKey(com.rosyoki.spring.boot.sample.app.jooq.public_.Keys.CONSTRAINT_4, UserDetail.USER_DETAIL, "user_detail_ibfk_1", UserDetail.USER_DETAIL.USERS_ID);
    }
}
