/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.public_;


import com.rosyoki.spring.boot.sample.app.jooq.DefaultCatalog;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -640749015;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.post_zip_data</code>.
     */
    public final PostZipData POST_ZIP_DATA = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData.POST_ZIP_DATA;

    /**
     * The table <code>public.user_detail</code>.
     */
    public final UserDetail USER_DETAIL = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail.USER_DETAIL;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            PostZipData.POST_ZIP_DATA,
            UserDetail.USER_DETAIL,
            Users.USERS);
    }
}
