/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.public_;


import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail;
import com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.post_zip_data</code>.
     */
    public static final PostZipData POST_ZIP_DATA = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.PostZipData.POST_ZIP_DATA;

    /**
     * The table <code>public.user_detail</code>.
     */
    public static final UserDetail USER_DETAIL = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.UserDetail.USER_DETAIL;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.rosyoki.spring.boot.sample.app.jooq.public_.tables.Users.USERS;
}
