/*
 * This file is generated by jOOQ.
*/
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUser extends TableImpl<AuthUserRecord> {

    private static final long serialVersionUID = -567685087;

    /**
     * The reference instance of <code>blog_db.auth_user</code>
     */
    public static final AuthUser AUTH_USER = new AuthUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthUserRecord> getRecordType() {
        return AuthUserRecord.class;
    }

    /**
     * The column <code>blog_db.auth_user.id</code>.
     */
    public final TableField<AuthUserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_user.password</code>.
     */
    public final TableField<AuthUserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.last_login</code>.
     */
    public final TableField<AuthUserRecord, Timestamp> LAST_LOGIN = createField("last_login", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>blog_db.auth_user.is_superuser</code>.
     */
    public final TableField<AuthUserRecord, Byte> IS_SUPERUSER = createField("is_superuser", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.username</code>.
     */
    public final TableField<AuthUserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.first_name</code>.
     */
    public final TableField<AuthUserRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.last_name</code>.
     */
    public final TableField<AuthUserRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.email</code>.
     */
    public final TableField<AuthUserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(254).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.is_staff</code>.
     */
    public final TableField<AuthUserRecord, Byte> IS_STAFF = createField("is_staff", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.is_active</code>.
     */
    public final TableField<AuthUserRecord, Byte> IS_ACTIVE = createField("is_active", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user.date_joined</code>.
     */
    public final TableField<AuthUserRecord, Timestamp> DATE_JOINED = createField("date_joined", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_user</code> table reference
     */
    public AuthUser() {
        this(DSL.name("auth_user"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_user</code> table reference
     */
    public AuthUser(String alias) {
        this(DSL.name(alias), AUTH_USER);
    }

    /**
     * Create an aliased <code>blog_db.auth_user</code> table reference
     */
    public AuthUser(Name alias) {
        this(alias, AUTH_USER);
    }

    private AuthUser(Name alias, Table<AuthUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthUser(Name alias, Table<AuthUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_USER_PRIMARY, Indexes.AUTH_USER_USERNAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthUserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthUserRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthUserRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthUserRecord>>asList(Keys.KEY_AUTH_USER_PRIMARY, Keys.KEY_AUTH_USER_USERNAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUser as(String alias) {
        return new AuthUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUser as(Name alias) {
        return new AuthUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUser rename(String name) {
        return new AuthUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUser rename(Name name) {
        return new AuthUser(name, null);
    }
}
