/*
 * This file is generated by jOOQ.
*/
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserUserPermissionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUserUserPermissions extends TableImpl<AuthUserUserPermissionsRecord> {

    private static final long serialVersionUID = -115249813;

    /**
     * The reference instance of <code>blog_db.auth_user_user_permissions</code>
     */
    public static final AuthUserUserPermissions AUTH_USER_USER_PERMISSIONS = new AuthUserUserPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthUserUserPermissionsRecord> getRecordType() {
        return AuthUserUserPermissionsRecord.class;
    }

    /**
     * The column <code>blog_db.auth_user_user_permissions.id</code>.
     */
    public final TableField<AuthUserUserPermissionsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_user_user_permissions.user_id</code>.
     */
    public final TableField<AuthUserUserPermissionsRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user_user_permissions.permission_id</code>.
     */
    public final TableField<AuthUserUserPermissionsRecord, Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_user_user_permissions</code> table reference
     */
    public AuthUserUserPermissions() {
        this(DSL.name("auth_user_user_permissions"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_user_user_permissions</code> table reference
     */
    public AuthUserUserPermissions(String alias) {
        this(DSL.name(alias), AUTH_USER_USER_PERMISSIONS);
    }

    /**
     * Create an aliased <code>blog_db.auth_user_user_permissions</code> table reference
     */
    public AuthUserUserPermissions(Name alias) {
        this(alias, AUTH_USER_USER_PERMISSIONS);
    }

    private AuthUserUserPermissions(Name alias, Table<AuthUserUserPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthUserUserPermissions(Name alias, Table<AuthUserUserPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ, Indexes.AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM, Indexes.AUTH_USER_USER_PERMISSIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthUserUserPermissionsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_USER_USER_PERMISSIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthUserUserPermissionsRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_USER_USER_PERMISSIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthUserUserPermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthUserUserPermissionsRecord>>asList(Keys.KEY_AUTH_USER_USER_PERMISSIONS_PRIMARY, Keys.KEY_AUTH_USER_USER_PERMISSIONS_AUTH_USER_USER_PERMISSIONS_USER_ID_PERMISSION_ID_14A6B632_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AuthUserUserPermissionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AuthUserUserPermissionsRecord, ?>>asList(Keys.AUTH_USER_USER_PERMISSIONS_USER_ID_A95EAD1B_FK_AUTH_USER_ID, Keys.AUTH_USER_USER_PERMI_PERMISSION_ID_1FBB5F2C_FK_AUTH_PERM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUserUserPermissions as(String alias) {
        return new AuthUserUserPermissions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUserUserPermissions as(Name alias) {
        return new AuthUserUserPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserUserPermissions rename(String name) {
        return new AuthUserUserPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserUserPermissions rename(Name name) {
        return new AuthUserUserPermissions(name, null);
    }
}
