/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthUserGroupsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthUserGroups extends TableImpl<AuthUserGroupsRecord> {

    private static final long serialVersionUID = -499424853;

    /**
     * The reference instance of <code>blog_db.auth_user_groups</code>
     */
    public static final AuthUserGroups AUTH_USER_GROUPS = new AuthUserGroups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthUserGroupsRecord> getRecordType() {
        return AuthUserGroupsRecord.class;
    }

    /**
     * The column <code>blog_db.auth_user_groups.id</code>.
     */
    public final TableField<AuthUserGroupsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_user_groups.user_id</code>.
     */
    public final TableField<AuthUserGroupsRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_user_groups.group_id</code>.
     */
    public final TableField<AuthUserGroupsRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_user_groups</code> table reference
     */
    public AuthUserGroups() {
        this(DSL.name("auth_user_groups"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_user_groups</code> table reference
     */
    public AuthUserGroups(String alias) {
        this(DSL.name(alias), AUTH_USER_GROUPS);
    }

    /**
     * Create an aliased <code>blog_db.auth_user_groups</code> table reference
     */
    public AuthUserGroups(Name alias) {
        this(alias, AUTH_USER_GROUPS);
    }

    private AuthUserGroups(Name alias, Table<AuthUserGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthUserGroups(Name alias, Table<AuthUserGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AuthUserGroups(Table<O> child, ForeignKey<O, AuthUserGroupsRecord> key) {
        super(child, key, AUTH_USER_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_USER_GROUPS_AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID, Indexes.AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ, Indexes.AUTH_USER_GROUPS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthUserGroupsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_USER_GROUPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthUserGroupsRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_USER_GROUPS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthUserGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthUserGroupsRecord>>asList(Keys.KEY_AUTH_USER_GROUPS_PRIMARY, Keys.KEY_AUTH_USER_GROUPS_AUTH_USER_GROUPS_USER_ID_GROUP_ID_94350C0C_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AuthUserGroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AuthUserGroupsRecord, ?>>asList(Keys.AUTH_USER_GROUPS_USER_ID_6A12ED8B_FK_AUTH_USER_ID, Keys.AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID);
    }

    public AuthUser authUser() {
        return new AuthUser(this, Keys.AUTH_USER_GROUPS_USER_ID_6A12ED8B_FK_AUTH_USER_ID);
    }

    public AuthGroup authGroup() {
        return new AuthGroup(this, Keys.AUTH_USER_GROUPS_GROUP_ID_97559544_FK_AUTH_GROUP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUserGroups as(String alias) {
        return new AuthUserGroups(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthUserGroups as(Name alias) {
        return new AuthUserGroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserGroups rename(String name) {
        return new AuthUserGroups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserGroups rename(Name name) {
        return new AuthUserGroups(name, null);
    }
}
