/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthGroup extends TableImpl<AuthGroupRecord> {

    private static final long serialVersionUID = -1307622250;

    /**
     * The reference instance of <code>blog_db.auth_group</code>
     */
    public static final AuthGroup AUTH_GROUP = new AuthGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthGroupRecord> getRecordType() {
        return AuthGroupRecord.class;
    }

    /**
     * The column <code>blog_db.auth_group.id</code>.
     */
    public final TableField<AuthGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_group.name</code>.
     */
    public final TableField<AuthGroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_group</code> table reference
     */
    public AuthGroup() {
        this(DSL.name("auth_group"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_group</code> table reference
     */
    public AuthGroup(String alias) {
        this(DSL.name(alias), AUTH_GROUP);
    }

    /**
     * Create an aliased <code>blog_db.auth_group</code> table reference
     */
    public AuthGroup(Name alias) {
        this(alias, AUTH_GROUP);
    }

    private AuthGroup(Name alias, Table<AuthGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthGroup(Name alias, Table<AuthGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AuthGroup(Table<O> child, ForeignKey<O, AuthGroupRecord> key) {
        super(child, key, AUTH_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_GROUP_NAME, Indexes.AUTH_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthGroupRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthGroupRecord>>asList(Keys.KEY_AUTH_GROUP_PRIMARY, Keys.KEY_AUTH_GROUP_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroup as(String alias) {
        return new AuthGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroup as(Name alias) {
        return new AuthGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthGroup rename(String name) {
        return new AuthGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthGroup rename(Name name) {
        return new AuthGroup(name, null);
    }
}
