/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthGroupPermissionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthGroupPermissions extends TableImpl<AuthGroupPermissionsRecord> {

    private static final long serialVersionUID = -2000122782;

    /**
     * The reference instance of <code>blog_db.auth_group_permissions</code>
     */
    public static final AuthGroupPermissions AUTH_GROUP_PERMISSIONS = new AuthGroupPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthGroupPermissionsRecord> getRecordType() {
        return AuthGroupPermissionsRecord.class;
    }

    /**
     * The column <code>blog_db.auth_group_permissions.id</code>.
     */
    public final TableField<AuthGroupPermissionsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_group_permissions.group_id</code>.
     */
    public final TableField<AuthGroupPermissionsRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_group_permissions.permission_id</code>.
     */
    public final TableField<AuthGroupPermissionsRecord, Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_group_permissions</code> table reference
     */
    public AuthGroupPermissions() {
        this(DSL.name("auth_group_permissions"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_group_permissions</code> table reference
     */
    public AuthGroupPermissions(String alias) {
        this(DSL.name(alias), AUTH_GROUP_PERMISSIONS);
    }

    /**
     * Create an aliased <code>blog_db.auth_group_permissions</code> table reference
     */
    public AuthGroupPermissions(Name alias) {
        this(alias, AUTH_GROUP_PERMISSIONS);
    }

    private AuthGroupPermissions(Name alias, Table<AuthGroupPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthGroupPermissions(Name alias, Table<AuthGroupPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AuthGroupPermissions(Table<O> child, ForeignKey<O, AuthGroupPermissionsRecord> key) {
        super(child, key, AUTH_GROUP_PERMISSIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ, Indexes.AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM, Indexes.AUTH_GROUP_PERMISSIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthGroupPermissionsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_GROUP_PERMISSIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthGroupPermissionsRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_GROUP_PERMISSIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthGroupPermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthGroupPermissionsRecord>>asList(Keys.KEY_AUTH_GROUP_PERMISSIONS_PRIMARY, Keys.KEY_AUTH_GROUP_PERMISSIONS_AUTH_GROUP_PERMISSIONS_GROUP_ID_PERMISSION_ID_0CD325B0_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AuthGroupPermissionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AuthGroupPermissionsRecord, ?>>asList(Keys.AUTH_GROUP_PERMISSIONS_GROUP_ID_B120CBF9_FK_AUTH_GROUP_ID, Keys.AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM);
    }

    public AuthGroup authGroup() {
        return new AuthGroup(this, Keys.AUTH_GROUP_PERMISSIONS_GROUP_ID_B120CBF9_FK_AUTH_GROUP_ID);
    }

    public AuthPermission authPermission() {
        return new AuthPermission(this, Keys.AUTH_GROUP_PERMISSIO_PERMISSION_ID_84C5C92E_FK_AUTH_PERM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissions as(String alias) {
        return new AuthGroupPermissions(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissions as(Name alias) {
        return new AuthGroupPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthGroupPermissions rename(String name) {
        return new AuthGroupPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthGroupPermissions rename(Name name) {
        return new AuthGroupPermissions(name, null);
    }
}
