/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.AuthPermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthPermission extends TableImpl<AuthPermissionRecord> {

    private static final long serialVersionUID = 416401391;

    /**
     * The reference instance of <code>blog_db.auth_permission</code>
     */
    public static final AuthPermission AUTH_PERMISSION = new AuthPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthPermissionRecord> getRecordType() {
        return AuthPermissionRecord.class;
    }

    /**
     * The column <code>blog_db.auth_permission.id</code>.
     */
    public final TableField<AuthPermissionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.auth_permission.name</code>.
     */
    public final TableField<AuthPermissionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_permission.content_type_id</code>.
     */
    public final TableField<AuthPermissionRecord, Integer> CONTENT_TYPE_ID = createField("content_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>blog_db.auth_permission.codename</code>.
     */
    public final TableField<AuthPermissionRecord, String> CODENAME = createField("codename", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>blog_db.auth_permission</code> table reference
     */
    public AuthPermission() {
        this(DSL.name("auth_permission"), null);
    }

    /**
     * Create an aliased <code>blog_db.auth_permission</code> table reference
     */
    public AuthPermission(String alias) {
        this(DSL.name(alias), AUTH_PERMISSION);
    }

    /**
     * Create an aliased <code>blog_db.auth_permission</code> table reference
     */
    public AuthPermission(Name alias) {
        this(alias, AUTH_PERMISSION);
    }

    private AuthPermission(Name alias, Table<AuthPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthPermission(Name alias, Table<AuthPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AuthPermission(Table<O> child, ForeignKey<O, AuthPermissionRecord> key) {
        super(child, key, AUTH_PERMISSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ, Indexes.AUTH_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthPermissionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTH_PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthPermissionRecord> getPrimaryKey() {
        return Keys.KEY_AUTH_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthPermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthPermissionRecord>>asList(Keys.KEY_AUTH_PERMISSION_PRIMARY, Keys.KEY_AUTH_PERMISSION_AUTH_PERMISSION_CONTENT_TYPE_ID_CODENAME_01AB375A_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AuthPermissionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AuthPermissionRecord, ?>>asList(Keys.AUTH_PERMISSION_CONTENT_TYPE_ID_2F476E4B_FK_DJANGO_CO);
    }

    public DjangoContentType djangoContentType() {
        return new DjangoContentType(this, Keys.AUTH_PERMISSION_CONTENT_TYPE_ID_2F476E4B_FK_DJANGO_CO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthPermission as(String alias) {
        return new AuthPermission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthPermission as(Name alias) {
        return new AuthPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthPermission rename(String name) {
        return new AuthPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthPermission rename(Name name) {
        return new AuthPermission(name, null);
    }
}
