/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoContentTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoContentType extends TableImpl<DjangoContentTypeRecord> {

    private static final long serialVersionUID = -1593008049;

    /**
     * The reference instance of <code>blog_db.django_content_type</code>
     */
    public static final DjangoContentType DJANGO_CONTENT_TYPE = new DjangoContentType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjangoContentTypeRecord> getRecordType() {
        return DjangoContentTypeRecord.class;
    }

    /**
     * The column <code>blog_db.django_content_type.id</code>.
     */
    public final TableField<DjangoContentTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.django_content_type.app_label</code>.
     */
    public final TableField<DjangoContentTypeRecord, String> APP_LABEL = createField("app_label", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>blog_db.django_content_type.model</code>.
     */
    public final TableField<DjangoContentTypeRecord, String> MODEL = createField("model", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>blog_db.django_content_type</code> table reference
     */
    public DjangoContentType() {
        this(DSL.name("django_content_type"), null);
    }

    /**
     * Create an aliased <code>blog_db.django_content_type</code> table reference
     */
    public DjangoContentType(String alias) {
        this(DSL.name(alias), DJANGO_CONTENT_TYPE);
    }

    /**
     * Create an aliased <code>blog_db.django_content_type</code> table reference
     */
    public DjangoContentType(Name alias) {
        this(alias, DJANGO_CONTENT_TYPE);
    }

    private DjangoContentType(Name alias, Table<DjangoContentTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjangoContentType(Name alias, Table<DjangoContentTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DjangoContentType(Table<O> child, ForeignKey<O, DjangoContentTypeRecord> key) {
        super(child, key, DJANGO_CONTENT_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ, Indexes.DJANGO_CONTENT_TYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DjangoContentTypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DJANGO_CONTENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjangoContentTypeRecord> getPrimaryKey() {
        return Keys.KEY_DJANGO_CONTENT_TYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjangoContentTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<DjangoContentTypeRecord>>asList(Keys.KEY_DJANGO_CONTENT_TYPE_PRIMARY, Keys.KEY_DJANGO_CONTENT_TYPE_DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentType as(String alias) {
        return new DjangoContentType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentType as(Name alias) {
        return new DjangoContentType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoContentType rename(String name) {
        return new DjangoContentType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoContentType rename(Name name) {
        return new DjangoContentType(name, null);
    }
}
