/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoSessionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoSession extends TableImpl<DjangoSessionRecord> {

    private static final long serialVersionUID = 94149319;

    /**
     * The reference instance of <code>blog_db.django_session</code>
     */
    public static final DjangoSession DJANGO_SESSION = new DjangoSession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjangoSessionRecord> getRecordType() {
        return DjangoSessionRecord.class;
    }

    /**
     * The column <code>blog_db.django_session.session_key</code>.
     */
    public final TableField<DjangoSessionRecord, String> SESSION_KEY = createField("session_key", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>blog_db.django_session.session_data</code>.
     */
    public final TableField<DjangoSessionRecord, String> SESSION_DATA = createField("session_data", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>blog_db.django_session.expire_date</code>.
     */
    public final TableField<DjangoSessionRecord, Timestamp> EXPIRE_DATE = createField("expire_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>blog_db.django_session</code> table reference
     */
    public DjangoSession() {
        this(DSL.name("django_session"), null);
    }

    /**
     * Create an aliased <code>blog_db.django_session</code> table reference
     */
    public DjangoSession(String alias) {
        this(DSL.name(alias), DJANGO_SESSION);
    }

    /**
     * Create an aliased <code>blog_db.django_session</code> table reference
     */
    public DjangoSession(Name alias) {
        this(alias, DJANGO_SESSION);
    }

    private DjangoSession(Name alias, Table<DjangoSessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjangoSession(Name alias, Table<DjangoSessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DjangoSession(Table<O> child, ForeignKey<O, DjangoSessionRecord> key) {
        super(child, key, DJANGO_SESSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJANGO_SESSION_DJANGO_SESSION_EXPIRE_DATE_A5C62663, Indexes.DJANGO_SESSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjangoSessionRecord> getPrimaryKey() {
        return Keys.KEY_DJANGO_SESSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjangoSessionRecord>> getKeys() {
        return Arrays.<UniqueKey<DjangoSessionRecord>>asList(Keys.KEY_DJANGO_SESSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSession as(String alias) {
        return new DjangoSession(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSession as(Name alias) {
        return new DjangoSession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoSession rename(String name) {
        return new DjangoSession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoSession rename(Name name) {
        return new DjangoSession(name, null);
    }
}
