/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.DjangoAdminLogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoAdminLog extends TableImpl<DjangoAdminLogRecord> {

    private static final long serialVersionUID = -2042732242;

    /**
     * The reference instance of <code>blog_db.django_admin_log</code>
     */
    public static final DjangoAdminLog DJANGO_ADMIN_LOG = new DjangoAdminLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjangoAdminLogRecord> getRecordType() {
        return DjangoAdminLogRecord.class;
    }

    /**
     * The column <code>blog_db.django_admin_log.id</code>.
     */
    public final TableField<DjangoAdminLogRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>blog_db.django_admin_log.action_time</code>.
     */
    public final TableField<DjangoAdminLogRecord, Timestamp> ACTION_TIME = createField("action_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>blog_db.django_admin_log.object_id</code>.
     */
    public final TableField<DjangoAdminLogRecord, String> OBJECT_ID = createField("object_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>blog_db.django_admin_log.object_repr</code>.
     */
    public final TableField<DjangoAdminLogRecord, String> OBJECT_REPR = createField("object_repr", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>blog_db.django_admin_log.action_flag</code>.
     */
    public final TableField<DjangoAdminLogRecord, UShort> ACTION_FLAG = createField("action_flag", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>blog_db.django_admin_log.change_message</code>.
     */
    public final TableField<DjangoAdminLogRecord, String> CHANGE_MESSAGE = createField("change_message", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>blog_db.django_admin_log.content_type_id</code>.
     */
    public final TableField<DjangoAdminLogRecord, Integer> CONTENT_TYPE_ID = createField("content_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>blog_db.django_admin_log.user_id</code>.
     */
    public final TableField<DjangoAdminLogRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>blog_db.django_admin_log</code> table reference
     */
    public DjangoAdminLog() {
        this(DSL.name("django_admin_log"), null);
    }

    /**
     * Create an aliased <code>blog_db.django_admin_log</code> table reference
     */
    public DjangoAdminLog(String alias) {
        this(DSL.name(alias), DJANGO_ADMIN_LOG);
    }

    /**
     * Create an aliased <code>blog_db.django_admin_log</code> table reference
     */
    public DjangoAdminLog(Name alias) {
        this(alias, DJANGO_ADMIN_LOG);
    }

    private DjangoAdminLog(Name alias, Table<DjangoAdminLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjangoAdminLog(Name alias, Table<DjangoAdminLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DjangoAdminLog(Table<O> child, ForeignKey<O, DjangoAdminLogRecord> key) {
        super(child, key, DJANGO_ADMIN_LOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO, Indexes.DJANGO_ADMIN_LOG_DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK, Indexes.DJANGO_ADMIN_LOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DjangoAdminLogRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DJANGO_ADMIN_LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DjangoAdminLogRecord> getPrimaryKey() {
        return Keys.KEY_DJANGO_ADMIN_LOG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DjangoAdminLogRecord>> getKeys() {
        return Arrays.<UniqueKey<DjangoAdminLogRecord>>asList(Keys.KEY_DJANGO_ADMIN_LOG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DjangoAdminLogRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DjangoAdminLogRecord, ?>>asList(Keys.DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO, Keys.DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK);
    }

    public DjangoContentType djangoContentType() {
        return new DjangoContentType(this, Keys.DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO);
    }

    public AuthUser authUser() {
        return new AuthUser(this, Keys.DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLog as(String alias) {
        return new DjangoAdminLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLog as(Name alias) {
        return new DjangoAdminLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoAdminLog rename(String name) {
        return new DjangoAdminLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoAdminLog rename(Name name) {
        return new DjangoAdminLog(name, null);
    }
}
