/*
 * This file is generated by jOOQ.
*/
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.PostZipDataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostZipData extends TableImpl<PostZipDataRecord> {

    private static final long serialVersionUID = -92304024;

    /**
     * The reference instance of <code>blog_db.post_zip_data</code>
     */
    public static final PostZipData POST_ZIP_DATA = new PostZipData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostZipDataRecord> getRecordType() {
        return PostZipDataRecord.class;
    }

    /**
     * The column <code>blog_db.post_zip_data.id</code>.
     */
    public final TableField<PostZipDataRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>blog_db.post_zip_data.old_zip</code>.
     */
    public final TableField<PostZipDataRecord, String> OLD_ZIP = createField("old_zip", org.jooq.impl.SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>blog_db.post_zip_data.zip</code>.
     */
    public final TableField<PostZipDataRecord, String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR(7), this, "");

    /**
     * The column <code>blog_db.post_zip_data.pref</code>.
     */
    public final TableField<PostZipDataRecord, String> PREF = createField("pref", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>blog_db.post_zip_data.city</code>.
     */
    public final TableField<PostZipDataRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>blog_db.post_zip_data.town</code>.
     */
    public final TableField<PostZipDataRecord, String> TOWN = createField("town", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>blog_db.post_zip_data</code> table reference
     */
    public PostZipData() {
        this(DSL.name("post_zip_data"), null);
    }

    /**
     * Create an aliased <code>blog_db.post_zip_data</code> table reference
     */
    public PostZipData(String alias) {
        this(DSL.name(alias), POST_ZIP_DATA);
    }

    /**
     * Create an aliased <code>blog_db.post_zip_data</code> table reference
     */
    public PostZipData(Name alias) {
        this(alias, POST_ZIP_DATA);
    }

    private PostZipData(Name alias, Table<PostZipDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private PostZipData(Name alias, Table<PostZipDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POST_ZIP_DATA_CITY, Indexes.POST_ZIP_DATA_POST_CITY_INDEX, Indexes.POST_ZIP_DATA_POST_CITY_TOWN_INDEX, Indexes.POST_ZIP_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostZipDataRecord> getPrimaryKey() {
        return Keys.KEY_POST_ZIP_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostZipDataRecord>> getKeys() {
        return Arrays.<UniqueKey<PostZipDataRecord>>asList(Keys.KEY_POST_ZIP_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipData as(String alias) {
        return new PostZipData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipData as(Name alias) {
        return new PostZipData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PostZipData rename(String name) {
        return new PostZipData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PostZipData rename(Name name) {
        return new PostZipData(name, null);
    }
}
