/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.BlogDb;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.Keys;
import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records.UserDetailRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetail extends TableImpl<UserDetailRecord> {

    private static final long serialVersionUID = 910444401;

    /**
     * The reference instance of <code>blog_db.user_detail</code>
     */
    public static final UserDetail USER_DETAIL = new UserDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDetailRecord> getRecordType() {
        return UserDetailRecord.class;
    }

    /**
     * The column <code>blog_db.user_detail.USERS_ID</code>.
     */
    public final TableField<UserDetailRecord, Long> USERS_ID = createField("USERS_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>blog_db.user_detail.FIRST_NAME</code>.
     */
    public final TableField<UserDetailRecord, String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.LAST_NAME</code>.
     */
    public final TableField<UserDetailRecord, String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.EML_NAME</code>.
     */
    public final TableField<UserDetailRecord, String> EML_NAME = createField("EML_NAME", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>blog_db.user_detail.EML_DOMAIN</code>.
     */
    public final TableField<UserDetailRecord, String> EML_DOMAIN = createField("EML_DOMAIN", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.POST_CODE</code>.
     */
    public final TableField<UserDetailRecord, String> POST_CODE = createField("POST_CODE", org.jooq.impl.SQLDataType.VARCHAR(7), this, "");

    /**
     * The column <code>blog_db.user_detail.PRE_CODE</code>.
     */
    public final TableField<UserDetailRecord, Integer> PRE_CODE = createField("PRE_CODE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>blog_db.user_detail.ADDRESS1</code>.
     */
    public final TableField<UserDetailRecord, String> ADDRESS1 = createField("ADDRESS1", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.ADDRESS2</code>.
     */
    public final TableField<UserDetailRecord, String> ADDRESS2 = createField("ADDRESS2", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.ADDRESS3</code>.
     */
    public final TableField<UserDetailRecord, String> ADDRESS3 = createField("ADDRESS3", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>blog_db.user_detail.created</code>.
     */
    public final TableField<UserDetailRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>blog_db.user_detail.modified</code>.
     */
    public final TableField<UserDetailRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>blog_db.user_detail</code> table reference
     */
    public UserDetail() {
        this(DSL.name("user_detail"), null);
    }

    /**
     * Create an aliased <code>blog_db.user_detail</code> table reference
     */
    public UserDetail(String alias) {
        this(DSL.name(alias), USER_DETAIL);
    }

    /**
     * Create an aliased <code>blog_db.user_detail</code> table reference
     */
    public UserDetail(Name alias) {
        this(alias, USER_DETAIL);
    }

    private UserDetail(Name alias, Table<UserDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserDetail(Name alias, Table<UserDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserDetail(Table<O> child, ForeignKey<O, UserDetailRecord> key) {
        super(child, key, USER_DETAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BlogDb.BLOG_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_DETAIL_EML_NAME, Indexes.USER_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserDetailRecord> getPrimaryKey() {
        return Keys.KEY_USER_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<UserDetailRecord>>asList(Keys.KEY_USER_DETAIL_PRIMARY, Keys.KEY_USER_DETAIL_EML_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserDetailRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserDetailRecord, ?>>asList(Keys.USER_DETAIL_IBFK_1);
    }

    public Users users() {
        return new Users(this, Keys.USER_DETAIL_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetail as(String alias) {
        return new UserDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetail as(Name alias) {
        return new UserDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDetail rename(String name) {
        return new UserDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserDetail rename(Name name) {
        return new UserDetail(name, null);
    }
}
