/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.information_schema;


import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Catalogs;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Collations;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.ColumnPrivileges;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Columns;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Constants;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Constraints;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.CrossReferences;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Domains;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.FunctionAliases;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.FunctionColumns;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Help;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.InDoubt;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Indexes;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.KeyColumnUsage;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Locks;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.QueryStatistics;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.ReferentialConstraints;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Rights;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Roles;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Schemata;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Sequences;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.SessionState;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Sessions;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Settings;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Synonyms;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TableConstraints;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TablePrivileges;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TableTypes;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Triggers;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TypeInfo;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Users;
import com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Views;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in information_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>information_schema.catalogs</code>.
     */
    public static final Catalogs CATALOGS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Catalogs.CATALOGS;

    /**
     * The table <code>information_schema.collations</code>.
     */
    public static final Collations COLLATIONS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>information_schema.column_privileges</code>.
     */
    public static final ColumnPrivileges COLUMN_PRIVILEGES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>information_schema.columns</code>.
     */
    public static final Columns COLUMNS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>information_schema.constants</code>.
     */
    public static final Constants CONSTANTS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Constants.CONSTANTS;

    /**
     * The table <code>information_schema.constraints</code>.
     */
    public static final Constraints CONSTRAINTS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Constraints.CONSTRAINTS;

    /**
     * The table <code>information_schema.cross_references</code>.
     */
    public static final CrossReferences CROSS_REFERENCES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.CrossReferences.CROSS_REFERENCES;

    /**
     * The table <code>information_schema.domains</code>.
     */
    public static final Domains DOMAINS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Domains.DOMAINS;

    /**
     * The table <code>information_schema.function_aliases</code>.
     */
    public static final FunctionAliases FUNCTION_ALIASES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

    /**
     * The table <code>information_schema.function_columns</code>.
     */
    public static final FunctionColumns FUNCTION_COLUMNS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

    /**
     * The table <code>information_schema.help</code>.
     */
    public static final Help HELP = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Help.HELP;

    /**
     * The table <code>information_schema.in_doubt</code>.
     */
    public static final InDoubt IN_DOUBT = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.InDoubt.IN_DOUBT;

    /**
     * The table <code>information_schema.indexes</code>.
     */
    public static final Indexes INDEXES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Indexes.INDEXES;

    /**
     * The table <code>information_schema.key_column_usage</code>.
     */
    public static final KeyColumnUsage KEY_COLUMN_USAGE = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

    /**
     * The table <code>information_schema.locks</code>.
     */
    public static final Locks LOCKS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Locks.LOCKS;

    /**
     * The table <code>information_schema.query_statistics</code>.
     */
    public static final QueryStatistics QUERY_STATISTICS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

    /**
     * The table <code>information_schema.referential_constraints</code>.
     */
    public static final ReferentialConstraints REFERENTIAL_CONSTRAINTS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

    /**
     * The table <code>information_schema.rights</code>.
     */
    public static final Rights RIGHTS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Rights.RIGHTS;

    /**
     * The table <code>information_schema.roles</code>.
     */
    public static final Roles ROLES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Roles.ROLES;

    /**
     * The table <code>information_schema.schemata</code>.
     */
    public static final Schemata SCHEMATA = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>information_schema.sequences</code>.
     */
    public static final Sequences SEQUENCES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Sequences.SEQUENCES;

    /**
     * The table <code>information_schema.session_state</code>.
     */
    public static final SessionState SESSION_STATE = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.SessionState.SESSION_STATE;

    /**
     * The table <code>information_schema.sessions</code>.
     */
    public static final Sessions SESSIONS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Sessions.SESSIONS;

    /**
     * The table <code>information_schema.settings</code>.
     */
    public static final Settings SETTINGS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Settings.SETTINGS;

    /**
     * The table <code>information_schema.synonyms</code>.
     */
    public static final Synonyms SYNONYMS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Synonyms.SYNONYMS;

    /**
     * The table <code>information_schema.table_constraints</code>.
     */
    public static final TableConstraints TABLE_CONSTRAINTS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

    /**
     * The table <code>information_schema.table_privileges</code>.
     */
    public static final TablePrivileges TABLE_PRIVILEGES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>information_schema.table_types</code>.
     */
    public static final TableTypes TABLE_TYPES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TableTypes.TABLE_TYPES;

    /**
     * The table <code>information_schema.tables</code>.
     */
    public static final com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Tables TABLES = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>information_schema.triggers</code>.
     */
    public static final Triggers TRIGGERS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>information_schema.type_info</code>.
     */
    public static final TypeInfo TYPE_INFO = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.TypeInfo.TYPE_INFO;

    /**
     * The table <code>information_schema.users</code>.
     */
    public static final Users USERS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Users.USERS;

    /**
     * The table <code>information_schema.views</code>.
     */
    public static final Views VIEWS = com.rosyoki.spring.boot.sample.app.jooq.information_schema.tables.Views.VIEWS;
}
