/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.AuthGroupPermissions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthGroupPermissionsRecord extends UpdatableRecordImpl<AuthGroupPermissionsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 533771156;

    /**
     * Setter for <code>blog_db.auth_group_permissions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.auth_group_permissions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.auth_group_permissions.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.auth_group_permissions.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>blog_db.auth_group_permissions.permission_id</code>.
     */
    public void setPermissionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.auth_group_permissions.permission_id</code>.
     */
    public Integer getPermissionId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AuthGroupPermissions.AUTH_GROUP_PERMISSIONS.PERMISSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPermissionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPermissionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissionsRecord value2(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissionsRecord value3(Integer value) {
        setPermissionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthGroupPermissionsRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthGroupPermissionsRecord
     */
    public AuthGroupPermissionsRecord() {
        super(AuthGroupPermissions.AUTH_GROUP_PERMISSIONS);
    }

    /**
     * Create a detached, initialised AuthGroupPermissionsRecord
     */
    public AuthGroupPermissionsRecord(Integer id, Integer groupId, Integer permissionId) {
        super(AuthGroupPermissions.AUTH_GROUP_PERMISSIONS);

        set(0, id);
        set(1, groupId);
        set(2, permissionId);
    }
}
