/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoAdminLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoAdminLogRecord extends UpdatableRecordImpl<DjangoAdminLogRecord> implements Record8<Integer, Timestamp, String, String, UShort, String, Integer, Integer> {

    private static final long serialVersionUID = 981283015;

    /**
     * Setter for <code>blog_db.django_admin_log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.action_time</code>.
     */
    public void setActionTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.action_time</code>.
     */
    public Timestamp getActionTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.object_id</code>.
     */
    public void setObjectId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.object_id</code>.
     */
    public String getObjectId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.object_repr</code>.
     */
    public void setObjectRepr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.object_repr</code>.
     */
    public String getObjectRepr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.action_flag</code>.
     */
    public void setActionFlag(UShort value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.action_flag</code>.
     */
    public UShort getActionFlag() {
        return (UShort) get(4);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.change_message</code>.
     */
    public void setChangeMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.change_message</code>.
     */
    public String getChangeMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.content_type_id</code>.
     */
    public void setContentTypeId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.content_type_id</code>.
     */
    public Integer getContentTypeId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>blog_db.django_admin_log.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.django_admin_log.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, String, String, UShort, String, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Timestamp, String, String, UShort, String, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.ACTION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.OBJECT_REPR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field5() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.ACTION_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.CHANGE_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.CONTENT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DjangoAdminLog.DJANGO_ADMIN_LOG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getActionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getObjectRepr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component5() {
        return getActionFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getChangeMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getContentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getActionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObjectRepr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value5() {
        return getActionFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getChangeMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getContentTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value2(Timestamp value) {
        setActionTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value3(String value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value4(String value) {
        setObjectRepr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value5(UShort value) {
        setActionFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value6(String value) {
        setChangeMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value7(Integer value) {
        setContentTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord value8(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoAdminLogRecord values(Integer value1, Timestamp value2, String value3, String value4, UShort value5, String value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjangoAdminLogRecord
     */
    public DjangoAdminLogRecord() {
        super(DjangoAdminLog.DJANGO_ADMIN_LOG);
    }

    /**
     * Create a detached, initialised DjangoAdminLogRecord
     */
    public DjangoAdminLogRecord(Integer id, Timestamp actionTime, String objectId, String objectRepr, UShort actionFlag, String changeMessage, Integer contentTypeId, Integer userId) {
        super(DjangoAdminLog.DJANGO_ADMIN_LOG);

        set(0, id);
        set(1, actionTime);
        set(2, objectId);
        set(3, objectRepr);
        set(4, actionFlag);
        set(5, changeMessage);
        set(6, contentTypeId);
        set(7, userId);
    }
}
