/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoSession;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoSessionRecord extends UpdatableRecordImpl<DjangoSessionRecord> implements Record3<String, String, Timestamp> {

    private static final long serialVersionUID = 430512365;

    /**
     * Setter for <code>blog_db.django_session.session_key</code>.
     */
    public void setSessionKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.django_session.session_key</code>.
     */
    public String getSessionKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>blog_db.django_session.session_data</code>.
     */
    public void setSessionData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.django_session.session_data</code>.
     */
    public String getSessionData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.django_session.expire_date</code>.
     */
    public void setExpireDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.django_session.expire_date</code>.
     */
    public Timestamp getExpireDate() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DjangoSession.DJANGO_SESSION.SESSION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DjangoSession.DJANGO_SESSION.SESSION_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DjangoSession.DJANGO_SESSION.EXPIRE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSessionKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSessionData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSessionKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSessionData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSessionRecord value1(String value) {
        setSessionKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSessionRecord value2(String value) {
        setSessionData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSessionRecord value3(Timestamp value) {
        setExpireDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoSessionRecord values(String value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjangoSessionRecord
     */
    public DjangoSessionRecord() {
        super(DjangoSession.DJANGO_SESSION);
    }

    /**
     * Create a detached, initialised DjangoSessionRecord
     */
    public DjangoSessionRecord(String sessionKey, String sessionData, Timestamp expireDate) {
        super(DjangoSession.DJANGO_SESSION);

        set(0, sessionKey);
        set(1, sessionData);
        set(2, expireDate);
    }
}
