/*
 * This file is generated by jOOQ.
 */
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.DjangoContentType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoContentTypeRecord extends UpdatableRecordImpl<DjangoContentTypeRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1827461306;

    /**
     * Setter for <code>blog_db.django_content_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.django_content_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog_db.django_content_type.app_label</code>.
     */
    public void setAppLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.django_content_type.app_label</code>.
     */
    public String getAppLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.django_content_type.model</code>.
     */
    public void setModel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.django_content_type.model</code>.
     */
    public String getModel() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DjangoContentType.DJANGO_CONTENT_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DjangoContentType.DJANGO_CONTENT_TYPE.APP_LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DjangoContentType.DJANGO_CONTENT_TYPE.MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentTypeRecord value2(String value) {
        setAppLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentTypeRecord value3(String value) {
        setModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DjangoContentTypeRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DjangoContentTypeRecord
     */
    public DjangoContentTypeRecord() {
        super(DjangoContentType.DJANGO_CONTENT_TYPE);
    }

    /**
     * Create a detached, initialised DjangoContentTypeRecord
     */
    public DjangoContentTypeRecord(Integer id, String appLabel, String model) {
        super(DjangoContentType.DJANGO_CONTENT_TYPE);

        set(0, id);
        set(1, appLabel);
        set(2, model);
    }
}
