/*
 * This file is generated by jOOQ.
*/
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.PostZipData;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostZipDataRecord extends UpdatableRecordImpl<PostZipDataRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 606931366;

    /**
     * Setter for <code>blog_db.post_zip_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>blog_db.post_zip_data.old_zip</code>.
     */
    public void setOldZip(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.old_zip</code>.
     */
    public String getOldZip() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.post_zip_data.zip</code>.
     */
    public void setZip(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.zip</code>.
     */
    public String getZip() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blog_db.post_zip_data.pref</code>.
     */
    public void setPref(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.pref</code>.
     */
    public String getPref() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blog_db.post_zip_data.city</code>.
     */
    public void setCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.city</code>.
     */
    public String getCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blog_db.post_zip_data.town</code>.
     */
    public void setTown(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.post_zip_data.town</code>.
     */
    public String getTown() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PostZipData.POST_ZIP_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PostZipData.POST_ZIP_DATA.OLD_ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PostZipData.POST_ZIP_DATA.ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PostZipData.POST_ZIP_DATA.PREF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PostZipData.POST_ZIP_DATA.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PostZipData.POST_ZIP_DATA.TOWN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOldZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOldZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPref();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTown();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value2(String value) {
        setOldZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value3(String value) {
        setZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value4(String value) {
        setPref(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value5(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord value6(String value) {
        setTown(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostZipDataRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostZipDataRecord
     */
    public PostZipDataRecord() {
        super(PostZipData.POST_ZIP_DATA);
    }

    /**
     * Create a detached, initialised PostZipDataRecord
     */
    public PostZipDataRecord(Long id, String oldZip, String zip, String pref, String city, String town) {
        super(PostZipData.POST_ZIP_DATA);

        set(0, id);
        set(1, oldZip);
        set(2, zip);
        set(3, pref);
        set(4, city);
        set(5, town);
    }
}
