/*
 * This file is generated by jOOQ.
*/
package com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.records;


import com.rosyoki.spring.boot.sample.app.jooq.blog_db.tables.UserDetail;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetailRecord extends UpdatableRecordImpl<UserDetailRecord> implements Record12<Long, String, String, String, String, String, Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1317998159;

    /**
     * Setter for <code>blog_db.user_detail.USERS_ID</code>.
     */
    public void setUsersId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.USERS_ID</code>.
     */
    public Long getUsersId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>blog_db.user_detail.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog_db.user_detail.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blog_db.user_detail.EML_NAME</code>.
     */
    public void setEmlName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.EML_NAME</code>.
     */
    public String getEmlName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blog_db.user_detail.EML_DOMAIN</code>.
     */
    public void setEmlDomain(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.EML_DOMAIN</code>.
     */
    public String getEmlDomain() {
        return (String) get(4);
    }

    /**
     * Setter for <code>blog_db.user_detail.POST_CODE</code>.
     */
    public void setPostCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.POST_CODE</code>.
     */
    public String getPostCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>blog_db.user_detail.PRE_CODE</code>.
     */
    public void setPreCode(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.PRE_CODE</code>.
     */
    public Integer getPreCode() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>blog_db.user_detail.ADDRESS1</code>.
     */
    public void setAddress1(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.ADDRESS1</code>.
     */
    public String getAddress1() {
        return (String) get(7);
    }

    /**
     * Setter for <code>blog_db.user_detail.ADDRESS2</code>.
     */
    public void setAddress2(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.ADDRESS2</code>.
     */
    public String getAddress2() {
        return (String) get(8);
    }

    /**
     * Setter for <code>blog_db.user_detail.ADDRESS3</code>.
     */
    public void setAddress3(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.ADDRESS3</code>.
     */
    public String getAddress3() {
        return (String) get(9);
    }

    /**
     * Setter for <code>blog_db.user_detail.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>blog_db.user_detail.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>blog_db.user_detail.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, String, String, String, String, Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserDetail.USER_DETAIL.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserDetail.USER_DETAIL.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserDetail.USER_DETAIL.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserDetail.USER_DETAIL.EML_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserDetail.USER_DETAIL.EML_DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserDetail.USER_DETAIL.POST_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserDetail.USER_DETAIL.PRE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserDetail.USER_DETAIL.ADDRESS1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserDetail.USER_DETAIL.ADDRESS2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UserDetail.USER_DETAIL.ADDRESS3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return UserDetail.USER_DETAIL.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return UserDetail.USER_DETAIL.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmlName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEmlDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPostCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPreCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAddress3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmlName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmlDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPostCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPreCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAddress3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value1(Long value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value3(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value4(String value) {
        setEmlName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value5(String value) {
        setEmlDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value6(String value) {
        setPostCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value7(Integer value) {
        setPreCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value8(String value) {
        setAddress1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value9(String value) {
        setAddress2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value10(String value) {
        setAddress3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value11(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord value12(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDetailRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, String value9, String value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDetailRecord
     */
    public UserDetailRecord() {
        super(UserDetail.USER_DETAIL);
    }

    /**
     * Create a detached, initialised UserDetailRecord
     */
    public UserDetailRecord(Long usersId, String firstName, String lastName, String emlName, String emlDomain, String postCode, Integer preCode, String address1, String address2, String address3, Timestamp created, Timestamp modified) {
        super(UserDetail.USER_DETAIL);

        set(0, usersId);
        set(1, firstName);
        set(2, lastName);
        set(3, emlName);
        set(4, emlDomain);
        set(5, postCode);
        set(6, preCode);
        set(7, address1);
        set(8, address2);
        set(9, address3);
        set(10, created);
        set(11, modified);
    }
}
