package com.rosyoki.spring.boot.sample.app.entity;

import java.util.ArrayList;
import java.util.List;

public class PostZipDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public PostZipDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOldZipIsNull() {
            addCriterion("old_zip is null");
            return (Criteria) this;
        }

        public Criteria andOldZipIsNotNull() {
            addCriterion("old_zip is not null");
            return (Criteria) this;
        }

        public Criteria andOldZipEqualTo(String value) {
            addCriterion("old_zip =", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipNotEqualTo(String value) {
            addCriterion("old_zip <>", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipGreaterThan(String value) {
            addCriterion("old_zip >", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipGreaterThanOrEqualTo(String value) {
            addCriterion("old_zip >=", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipLessThan(String value) {
            addCriterion("old_zip <", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipLessThanOrEqualTo(String value) {
            addCriterion("old_zip <=", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipLike(String value) {
            addCriterion("old_zip like", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipNotLike(String value) {
            addCriterion("old_zip not like", value, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipIn(List<String> values) {
            addCriterion("old_zip in", values, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipNotIn(List<String> values) {
            addCriterion("old_zip not in", values, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipBetween(String value1, String value2) {
            addCriterion("old_zip between", value1, value2, "oldZip");
            return (Criteria) this;
        }

        public Criteria andOldZipNotBetween(String value1, String value2) {
            addCriterion("old_zip not between", value1, value2, "oldZip");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("zip is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("zip is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("zip =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("zip <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("zip >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("zip >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("zip <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("zip <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("zip like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("zip not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("zip in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("zip not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("zip between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("zip not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andPrefIsNull() {
            addCriterion("pref is null");
            return (Criteria) this;
        }

        public Criteria andPrefIsNotNull() {
            addCriterion("pref is not null");
            return (Criteria) this;
        }

        public Criteria andPrefEqualTo(String value) {
            addCriterion("pref =", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotEqualTo(String value) {
            addCriterion("pref <>", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThan(String value) {
            addCriterion("pref >", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefGreaterThanOrEqualTo(String value) {
            addCriterion("pref >=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThan(String value) {
            addCriterion("pref <", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLessThanOrEqualTo(String value) {
            addCriterion("pref <=", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefLike(String value) {
            addCriterion("pref like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotLike(String value) {
            addCriterion("pref not like", value, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefIn(List<String> values) {
            addCriterion("pref in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotIn(List<String> values) {
            addCriterion("pref not in", values, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefBetween(String value1, String value2) {
            addCriterion("pref between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andPrefNotBetween(String value1, String value2) {
            addCriterion("pref not between", value1, value2, "pref");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_zip_data
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 04 10:07:15 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}