package com.rosyoki.spring.boot.sample.app.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
public class PostZipData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.old_zip
     *
     * @mbg.generated
     */
    private String oldZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.zip
     *
     * @mbg.generated
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.pref
     *
     * @mbg.generated
     */
    private String pref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.town
     *
     * @mbg.generated
     */
    private String town;
}