package com.rosyoki.spring.boot.sample.app.entity;

public class PostZipData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.old_zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String oldZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.pref
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String pref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.city
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_zip_data.town
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String town;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.id
     *
     * @return the value of post_zip_data.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.id
     *
     * @param id the value for post_zip_data.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.old_zip
     *
     * @return the value of post_zip_data.old_zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getOldZip() {
        return oldZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.old_zip
     *
     * @param oldZip the value for post_zip_data.old_zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setOldZip(String oldZip) {
        this.oldZip = oldZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.zip
     *
     * @return the value of post_zip_data.zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.zip
     *
     * @param zip the value for post_zip_data.zip
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.pref
     *
     * @return the value of post_zip_data.pref
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getPref() {
        return pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.pref
     *
     * @param pref the value for post_zip_data.pref
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setPref(String pref) {
        this.pref = pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.city
     *
     * @return the value of post_zip_data.city
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.city
     *
     * @param city the value for post_zip_data.city
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_zip_data.town
     *
     * @return the value of post_zip_data.town
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_zip_data.town
     *
     * @param town the value for post_zip_data.town
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setTown(String town) {
        this.town = town;
    }
}