package com.rosyoki.spring.boot.sample.app.entity;

// Generated 2014/12/21 16:47:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "blog_db")
public class Users implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5225274134277627058L;
    
    private Integer id;
    private String loginName;
    private String passwd;
    private Date created;
    private Date modified;

    public Users() {
    }

    public Users(Date created, Date modified) {
        this.created = created;
        this.modified = modified;
    }

    public Users(String loginName, String passwd, Date created, Date modified,
            UserDetail userDetail) {
        this.loginName = loginName;
        this.passwd = passwd;
        this.created = created;
        this.modified = modified;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "login_name")
    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Column(name = "passwd")
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modified", nullable = false, length = 19)
    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }
}
