package com.rosyoki.spring.boot.sample.app.entity;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_name
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.passwd
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modified
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_name
     *
     * @return the value of users.login_name
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_name
     *
     * @param loginName the value for users.login_name
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.passwd
     *
     * @return the value of users.passwd
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.passwd
     *
     * @param passwd the value for users.passwd
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created
     *
     * @return the value of users.created
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created
     *
     * @param created the value for users.created
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modified
     *
     * @return the value of users.modified
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modified
     *
     * @param modified the value for users.modified
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}