package com.rosyoki.spring.boot.sample.app.entity;

import java.util.Date;

public class UserDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.USERS_ID
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Long usersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.FIRST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.LAST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.EML_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String emlName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.EML_DOMAIN
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String emlDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.POST_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.PRE_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Integer preCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.ADDRESS1
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.ADDRESS2
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.ADDRESS3
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private String address3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.CREATED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.MODIFIED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.USERS_ID
     *
     * @return the value of user_detail.USERS_ID
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Long getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.USERS_ID
     *
     * @param usersId the value for user_detail.USERS_ID
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setUsersId(Long usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.FIRST_NAME
     *
     * @return the value of user_detail.FIRST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.FIRST_NAME
     *
     * @param firstName the value for user_detail.FIRST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.LAST_NAME
     *
     * @return the value of user_detail.LAST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.LAST_NAME
     *
     * @param lastName the value for user_detail.LAST_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.EML_NAME
     *
     * @return the value of user_detail.EML_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getEmlName() {
        return emlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.EML_NAME
     *
     * @param emlName the value for user_detail.EML_NAME
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setEmlName(String emlName) {
        this.emlName = emlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.EML_DOMAIN
     *
     * @return the value of user_detail.EML_DOMAIN
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getEmlDomain() {
        return emlDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.EML_DOMAIN
     *
     * @param emlDomain the value for user_detail.EML_DOMAIN
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setEmlDomain(String emlDomain) {
        this.emlDomain = emlDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.POST_CODE
     *
     * @return the value of user_detail.POST_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.POST_CODE
     *
     * @param postCode the value for user_detail.POST_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.PRE_CODE
     *
     * @return the value of user_detail.PRE_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Integer getPreCode() {
        return preCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.PRE_CODE
     *
     * @param preCode the value for user_detail.PRE_CODE
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setPreCode(Integer preCode) {
        this.preCode = preCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.ADDRESS1
     *
     * @return the value of user_detail.ADDRESS1
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.ADDRESS1
     *
     * @param address1 the value for user_detail.ADDRESS1
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.ADDRESS2
     *
     * @return the value of user_detail.ADDRESS2
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.ADDRESS2
     *
     * @param address2 the value for user_detail.ADDRESS2
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.ADDRESS3
     *
     * @return the value of user_detail.ADDRESS3
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.ADDRESS3
     *
     * @param address3 the value for user_detail.ADDRESS3
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.CREATED
     *
     * @return the value of user_detail.CREATED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.CREATED
     *
     * @param created the value for user_detail.CREATED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.MODIFIED
     *
     * @return the value of user_detail.MODIFIED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.MODIFIED
     *
     * @param modified the value for user_detail.MODIFIED
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}