package com.rosyoki.spring.boot.sample.app.mapper;

import com.rosyoki.spring.boot.sample.app.entity.PostZipData;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PostZipDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int insert(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int insertSelective(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    PostZipData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostZipData record);

    PostZipData selectByNewCode(String newCode);

    List<PostZipData> selectByCity(String city);

    PostZipData selectByCityTown(@Param("city") String city, @Param("town") String town);

}