package com.rosyoki.spring.boot.sample.app.mapper;

import com.rosyoki.spring.boot.sample.app.entity.PostZipData;
import com.rosyoki.spring.boot.sample.app.entity.PostZipDataExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PostZipDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    long countByExample(PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int deleteByExample(PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int insert(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int insertSelective(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    List<PostZipData> selectByExampleWithBLOBs(PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    List<PostZipData> selectByExample(PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    PostZipData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByExampleSelective(@Param("record") PostZipData record, @Param("example") PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") PostZipData record, @Param("example") PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByExample(@Param("record") PostZipData record, @Param("example") PostZipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByPrimaryKeySelective(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PostZipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_zip_data
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByPrimaryKey(PostZipData record);
}