package com.rosyoki.spring.boot.sample.app.mapper;

import com.rosyoki.spring.boot.sample.app.entity.UserDetail;
import com.rosyoki.spring.boot.sample.app.entity.UserDetailExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    long countByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int deleteByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int deleteByPrimaryKey(Long usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    List<UserDetail> selectByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    UserDetail selectByPrimaryKey(Long usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByExampleSelective(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByExample(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sun Sep 04 10:07:15 JST 2016
     */
    int updateByPrimaryKey(UserDetail record);
}