package com.rosyoki.spring.boot.sample.app.users.entity;

// Generated 2014/12/21 16:47:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PostZipData generated by hbm2java
 */
@Entity
@Table(name = "post_zip_data", catalog = "blog_db")
public class PostZipData implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8612975531804578030L;
    
    private long id;
    private String oldZip;
    private String zip;
    private String pref;
    private String city;
    private String town;

    public PostZipData() {
    }

    public PostZipData(long id, String town) {
        this.id = id;
        this.town = town;
    }

    public PostZipData(long id, String oldZip, String zip, String pref,
            String city, String town) {
        this.id = id;
        this.oldZip = oldZip;
        this.zip = zip;
        this.pref = pref;
        this.city = city;
        this.town = town;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "old_zip", length = 5)
    public String getOldZip() {
        return this.oldZip;
    }

    public void setOldZip(String oldZip) {
        this.oldZip = oldZip;
    }

    @Column(name = "zip", length = 7)
    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    @Column(name = "pref", length = 65535)
    public String getPref() {
        return this.pref;
    }

    public void setPref(String pref) {
        this.pref = pref;
    }

    @Column(name = "city", length = 65535)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "town", nullable = false, length = 65535)
    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

}
