package com.rosyoki.spring.boot.sample.app.users.entity;

// Generated 2014/12/21 16:47:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserDetail generated by hbm2java
 */
@Entity
@Table(name = "user_detail", catalog = "blog_db", uniqueConstraints = @UniqueConstraint(columnNames = {
        "EML_NAME", "EML_DOMAIN" }))
public class UserDetail implements java.io.Serializable {

    private long usersId;
    private Users users;
    private String firstName;
    private String lastName;
    private String emlName;
    private String emlDomain;
    private String postCode;
    private Integer preCode;
    private String address1;
    private String address2;
    private String address3;
    private Date created;
    private Date modified;

    public UserDetail() {
    }

    public UserDetail(Users users, Date created, Date modified) {
        this.users = users;
        this.created = created;
        this.modified = modified;
    }

    public UserDetail(Users users, String firstName, String lastName,
            String emlName, String emlDomain, String postCode, Integer preCode,
            String address1, String address2, String address3, Date created,
            Date modified) {
        this.users = users;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emlName = emlName;
        this.emlDomain = emlDomain;
        this.postCode = postCode;
        this.preCode = preCode;
        this.address1 = address1;
        this.address2 = address2;
        this.address3 = address3;
        this.created = created;
        this.modified = modified;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "USERS_ID", unique = true, nullable = false)
    public long getUsersId() {
        return this.usersId;
    }

    public void setUsersId(long usersId) {
        this.usersId = usersId;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "FIRST_NAME")
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "EML_NAME", length = 32)
    public String getEmlName() {
        return this.emlName;
    }

    public void setEmlName(String emlName) {
        this.emlName = emlName;
    }

    @Column(name = "EML_DOMAIN")
    public String getEmlDomain() {
        return this.emlDomain;
    }

    public void setEmlDomain(String emlDomain) {
        this.emlDomain = emlDomain;
    }

    @Column(name = "POST_CODE", length = 7)
    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    @Column(name = "PRE_CODE")
    public Integer getPreCode() {
        return this.preCode;
    }

    public void setPreCode(Integer preCode) {
        this.preCode = preCode;
    }

    @Column(name = "ADDRESS1")
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name = "ADDRESS2")
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name = "ADDRESS3")
    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MODIFIED", nullable = false, length = 19)
    public Date getModified() {
        return this.modified;
    }

    public void setModified(Date modified) {
        this.modified = modified;
    }

}
